<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
<title><?php echo Mage::helper('invoicebank')->__('Title kvit') ?></title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="robots" content="noindex, nofollow, noarchive" />
<style type="text/css">
H1 {font-size: 12pt;}
p, ul, ol, h1 {margin-top:6px; margin-bottom:6px}
td {font-size: 9pt;}
small {font-size: 7pt;}
body {font-size: 10pt; background-color:#fff;}
</style>
</head>
<body>
<h3 style="color:#7A7F88;font-family:Tahoma;font-size:12px;">Квитанция для оплаты заказанного товара по счету через Сбербанк или любой другой банк.<br />
Распечатайте эту страницу, заполните фамилию и адрес, поставьте дату и подпись.</h3>
<table border="0" cellspacing="0" cellpadding="0" style="width:180mm; height:145mm;">
<tr valign="top">
    <td style="width:50mm; height:70mm; border:1pt solid #000000; border-bottom:none; border-right:none;" align="center">
    <b>Извещение</b><br>
    <font style="font-size:53mm">&nbsp;<br></font>
    <b>Кассир</b>
    </td>
    <td style="border:1pt solid #000000;border-bottom:none;" align="center">
        <table border="0" cellspacing="0" cellpadding="0" style="width:122mm; margin-top:3pt;">
            <tr>
                <td align="right"><small><i>Форма № ПД-4</i></small></td>
            </tr>
            <tr>
                <td style="border-bottom:1pt solid #000000;text-align:center;font-weight:bold;"><?php echo $this->getConfig('company'); ?></td>
            </tr>
            <tr>
                <td align="center"><small>(наименование получателя платежа)</small></td>
            </tr>
        </table>
        <table border="0" cellspacing="0" cellpadding="0" style="width:122mm; margin-top:3pt;">
            <tr>
                <td style="width:37mm; border-bottom:1pt solid #000000;text-align:center;"><?php echo $this->getConfig('inn'); ?>/<?php echo $this->getConfig('kpp'); ?></td>
                <td style="width:9mm;">&nbsp;</td>
                <td style="border-bottom:1pt solid #000000;text-align:center;font-weight:bold;"><?php echo $this->getConfig('nomer_scheta'); ?></td>
            </tr>
            <tr>
                <td align="center"><small>(ИНН/КПП)</small></td>
                <td><small>&nbsp;</small></td>
                <td align="center"><small>(номер счета получателя платежа)</small></td>
            </tr>
        </table>
        <table border="0" cellspacing="0" cellpadding="0" style="width:122mm; margin-top:3pt;">
            <tr>
                <td>в&nbsp;</td>
                <td style="width:73mm; border-bottom:1pt solid #000000;"><?php echo $this->getConfig('bank_name'); ?></td>
                <td align="right">БИК&nbsp;&nbsp;</td>
                <td style="width:33mm; border-bottom:1pt solid #000000;"><?php echo $this->getConfig('bank_bik'); ?></td>
            </tr>
            <tr>
                <td></td>
                <td align="center"><small>(наименование банка получателя платежа)</small></td>
                <td></td>
                <td></td>
            </tr>
        </table>
        <table border="0" cellspacing="0" cellpadding="0" style="width:122mm; margin-top:3pt;">
            <tr>
                <td width="1%" nowrap>Номер кор./сч. банка получателя платежа&nbsp;&nbsp;</td>
                <td width="100%" style="border-bottom:1pt solid #000000;"> <?php echo $this->getConfig('bank_korr_schet'); ?></td>
            </tr>
        </table>
        <table border="0" cellspacing="0" cellpadding="0" style="width:122mm; margin-top:3pt;">
            <tr>
                <td style="border-bottom:1pt solid #000000;text-align:center;font-weight:bold;"><?php echo Mage::helper('invoicebank')->__('Pay order') ?>
      <?php echo $this->getOrder()->getRealOrderId() ?>
      от
      <?php echo $this->formatDate($this->getOrder()->getCreatedAtStoreDate()) ?></td>

            </tr>
            <tr>
                <td  align="center"><small>(наименование платежа)</small></td>
            </tr>
        </table>
        <table border="0" cellspacing="0" cellpadding="0" style="width:122mm; margin-top:3pt;">
            <tr>
                <td width="1%" nowrap>Ф.И.О. плательщика&nbsp;&nbsp;</td>
                <td width="100%" style="border-bottom:1pt solid #000000;">&nbsp;</td>
            </tr>
        </table>
        <table border="0" cellspacing="0" cellpadding="0" style="width:122mm; margin-top:3pt;">
            <tr>
                <td width="1%" nowrap>Адрес плательщика&nbsp;&nbsp;</td>
                <td width="100%" style="border-bottom:1pt solid #000000;">&nbsp;</td>
            </tr>
        </table>
        <table border="0" cellspacing="0" cellpadding="0" style="width:122mm; margin-top:3pt;">
            <tr>
                <td>Сумма платежа&nbsp;&nbsp;<font style="font-weight:bold;"> <?php echo $this->getOrderSumm() ?> </font>&nbsp;<?php echo $this->getCurrencySymbol(); ?>&nbsp;<font style="font-weight:bold;"> <?php echo $this->getOrderSummKop() ?></font>&nbsp;коп.</td>
                <td align="right">&nbsp;&nbsp;Сумма платы за услуги&nbsp;&nbsp;_____&nbsp;<?php echo $this->getCurrencySymbol(); ?>&nbsp;____&nbsp;коп.</td>
            </tr>
        </table>
        <table border="0" cellspacing="0" cellpadding="0" style="width:122mm; margin-top:3pt;">
            <tr>
                <td>Итого&nbsp;&nbsp;_______&nbsp;<?php echo $this->getCurrencySymbol(); ?>&nbsp;____&nbsp;коп.</td>
                <td align="right">&nbsp;&nbsp;&laquo;______&raquo;________________ 201____ г.</td>
            </tr>
        </table>
        <table border="0" cellspacing="0" cellpadding="0" style="width:122mm; margin-top:3pt;">
            <tr>
                <td><small>С условиями приема указанной в платежном документе суммы,
                в т.ч. с суммой взимаемой платы за услуги банка, ознакомлен и согласен.</small></td>
            </tr>
        </table>
        <table border="0" cellspacing="0" cellpadding="0" style="width:122mm; margin-top:3pt;margin-bottom:3pt;">
            <tr>
                <td align="right"><b>Подпись плательщика _____________________</b></td>
            </tr>
        </table>
    </td>
</tr>
<tr valign="top">
    <td style="width:50mm; height:70mm; border:1pt solid #000000; border-right:none;" align="center">
    <b>Квитанция</b><br>
    <font style="font-size:53mm">&nbsp;<br></font>
    <b>Кассир</b>
    </td>
    <td style="border:1pt solid #000000;" align="center">
        <table border="0" cellspacing="0" cellpadding="0" style="width:122mm; margin-top:3pt;">
            <tr>
                <td align="right"><small><i>Форма № ПД-4</i></small></td>
            </tr>
            <tr>
                <td style="border-bottom:1pt solid #000000;text-align:center;font-weight:bold;"><?php echo $this->getConfig('company'); ?></td>
            </tr>
            <tr>
                <td align="center"><small>(наименование получателя платежа)</small></td>
            </tr>
        </table>
        <table border="0" cellspacing="0" cellpadding="0" style="width:122mm; margin-top:3pt;">
            <tr>
                <td style="width:37mm; border-bottom:1pt solid #000000;text-align:center;"><?php echo $this->getConfig('inn'); ?>/<?php echo $this->getConfig('kpp'); ?></td>
                <td style="width:9mm;">&nbsp;</td>
                <td style="border-bottom:1pt solid #000000;text-align:center;font-weight:bold;"><?php echo $this->getConfig('nomer_scheta'); ?></td>
            </tr>
            <tr>
                <td align="center"><small>(ИНН/КПП)</small></td>
                <td><small>&nbsp;</small></td>
                <td align="center"><small>(номер счета получателя платежа)</small></td>
            </tr>
        </table>
        <table border="0" cellspacing="0" cellpadding="0" style="width:122mm; margin-top:3pt;">
            <tr>
                <td>в&nbsp;</td>
                <td style="width:73mm; border-bottom:1pt solid #000000;"><?php echo $this->getConfig('bank_name'); ?></td>
                <td align="right">БИК&nbsp;&nbsp;</td>
                <td style="width:33mm; border-bottom:1pt solid #000000;"><?php echo $this->getConfig('bank_bik'); ?></td>
            </tr>
            <tr>
                <td></td>
                <td align="center"><small>(наименование банка получателя платежа)</small></td>
                <td></td>
                <td></td>
            </tr>
        </table>
        <table border="0" cellspacing="0" cellpadding="0" style="width:122mm; margin-top:3pt;">
            <tr>
                <td width="1%" nowrap>Номер кор./сч. банка получателя платежа&nbsp;&nbsp;</td>
                <td width="100%" style="border-bottom:1pt solid #000000;"> <?php echo $this->getConfig('bank_korr_schet'); ?></td>
            </tr>
        </table>
        <table border="0" cellspacing="0" cellpadding="0" style="width:122mm; margin-top:3pt;">
            <tr>
                <td style="border-bottom:1pt solid #000000;text-align:center;font-weight:bold;"><?php echo Mage::helper('invoicebank')->__('Pay order') ?>
      <?php echo $this->getOrder()->getRealOrderId() ?>
      от
      <?php echo $this->formatDate($this->getOrder()->getCreatedAtStoreDate()) ?></td>

            </tr>
            <tr>
                <td  align="center"><small>(наименование платежа)</small></td>
            </tr>
        </table>
        <table border="0" cellspacing="0" cellpadding="0" style="width:122mm; margin-top:3pt;">
            <tr>
                <td width="1%" nowrap>Ф.И.О. плательщика&nbsp;&nbsp;</td>
                <td width="100%" style="border-bottom:1pt solid #000000;">&nbsp;</td>
            </tr>
        </table>
        <table border="0" cellspacing="0" cellpadding="0" style="width:122mm; margin-top:3pt;">
            <tr>
                <td width="1%" nowrap>Адрес плательщика&nbsp;&nbsp;</td>
                <td width="100%" style="border-bottom:1pt solid #000000;">&nbsp;</td>
            </tr>
        </table>
        <table border="0" cellspacing="0" cellpadding="0" style="width:122mm; margin-top:3pt;">
            <tr>
                <td>Сумма платежа&nbsp;&nbsp;<font style="font-weight:bold;"> <?php echo $this->getOrderSumm() ?> </font>&nbsp;<?php echo $this->getCurrencySymbol(); ?>&nbsp;<font style="font-weight:bold;"> <?php echo $this->getOrderSummKop() ?></font>&nbsp;коп.</td>
                <td align="right">&nbsp;&nbsp;Сумма платы за услуги&nbsp;&nbsp;_____&nbsp;<?php echo $this->getCurrencySymbol(); ?>&nbsp;____&nbsp;коп.</td>
            </tr>
        </table>
        <table border="0" cellspacing="0" cellpadding="0" style="width:122mm; margin-top:3pt;">
            <tr>
                <td>Итого&nbsp;&nbsp;_______&nbsp;<?php echo $this->getCurrencySymbol(); ?>&nbsp;____&nbsp;коп.</td>
                <td align="right">&nbsp;&nbsp;&laquo;______&raquo;________________ 201____ г.</td>
            </tr>
        </table>
        <table border="0" cellspacing="0" cellpadding="0" style="width:122mm; margin-top:3pt;">
            <tr>
                <td><small>С условиями приема указанной в платежном документе суммы,
                в т.ч. с суммой взимаемой платы за услуги банка, ознакомлен и согласен.</small></td>
            </tr>
        </table>
        <table border="0" cellspacing="0" cellpadding="0" style="width:122mm; margin-top:3pt;margin-bottom:3pt;">
            <tr>
                <td align="right"><b>Подпись плательщика _____________________</b></td>
            </tr>
        </table>
    </td>
</tr>
</table>
<br />
<h1>Внимание! В стоимость заказа не включена комиссия банка.</h1>

<!-- Условия поставки -->
<h1><b>Метод оплаты:</b></h1>
<ol>
  <li>Распечатайте квитанцию. Если у вас нет принтера, перепишите верхнюю часть квитанции и заполните по этому образцу стандартный бланк квитанции в вашем банке.</li>
  <li>Вырежьте по контуру квитанцию.</li>
  <li>Оплатите квитанцию в любом отделении банка, принимающего платежи от частных лиц.</li>
  <li>Сохраните квитанцию до подтверждения исполнения заказа.</li>
</ol>
<?php echo $this->getConfig('desc');?>
</body>
</html>