<li class="<?php echo $this->getClassValue('country')?>  <?php if(!$this->hasAddressField('country')) :?>no-display<?php endif;?>">
  <div class="field">
      <label for="billing-country_id" class="for-required"><?php echo $this->__('Country') ?><em>*</em></label>
      <div class="input-box input-box-select">
          <?php echo $this->getCountryHtmlSelect('billing');?>
      </div>
  </div>
</li>