<?php if($this->hasAddressField('postcode')) :?>
    <li class="<?php echo $this->getClassValue('postcode')?>">
      <div class="field">
          <label for="postcode" class="for-required"><?php echo $this->__('Postcode') ?><em>*</em></label>
          <?php if($this->getPostcodeHelp()):?>
              <span class="f-right postcode-help"><a target="_blank" href="<?php echo $this->getPostcodeHelp()?>">Узнать свой индекс</a></span>
          <?php endif;?>
          <div class="input-box">
             <input autocomplete="off" type="text" data-error="<?php echo $this->__('Please enter the postcode.');?>" maxlength="6" title="<?php echo $this->__('Postcode') ?>" name="billing[postcode]" id="postcode" value="<?php echo $this->htmlEscape($this->getAddress()->getPostcode()) ?>" class="input-text validate-zip-international for-required" />
          </div>
      </div>
    </li>
<?php endif;?>