<div class="page-title">
    <h1><?php echo $this->__('An error occurred in the process of payment') ?></h1>
</div>
<?php if ($this->getRealOrderId()) : ?><p><?php echo $this->__('Order #') . $this->getRealOrderId() ?></p><?php endif ?>
<?php if ($this->isPaymentsLink()) : ?>
    <?php if($this->getReady()):?>
            <h4><a href="<?php echo $this->getInvoiceUrl(); ?>" target=_blank ><?php echo $this->__('Попробовать произвести оплату еще раз'); ?></a></h4>
    <?php else :?>
            <h4 style="color: #333333;"><?php echo $this->__('Your order is not confirmed by the manager'); ?></h4>
    <?php endif;?>
<?php endif;?>
<br />
<p><?php echo $this->__('Click <a href="%s">here</a> to continue shopping.', $this->getContinueShoppingUrl()) ?></p>
