<?php $_code = $this->getMethodCode() ?>
<ul id="payment_form_<?php echo $_code ?>" style="display:none" class="form-list">
    <li>
        <div class="input-box">
            <label for="<?php echo $_code ?>_tel"><?php echo $this->__('Phone') ?> <span class="required">*</span></label><br/>
            <input type="text" title="<?php echo $this->__('Phone') ?>" class="input-text required-entry" id="<?php echo $_code ?>_tel" name="payment[qiwi_phone]" value="<?php echo $this->getCurrentValue() ?>" />
            <small class="no-display"><?php echo $this->__('Primer 9219898888'); ?></small>
            <br />
        </div>
        <?php echo $this->__($this->getMethodDescription()); ?>
    </li>
</ul>
<?php if($this->isInputMask()):?>
    <script>
        jQuery("#qiwi_tel").inputmask("phone", {
            url: "<?php echo $this->getSkinUrl('js/qiwi/phone-codes.json')?>"
        });
    </script>
<?php endif;?>