<?php
    $store = Mage::app()->getStore();
    $code  = $store->getCode();

    $_helper    = $this->helper('catalog/output');
    $_category  = $this->getCurrentCategory();
    $_showcartbutton = Mage::getStoreConfig('porto_settings/category_grid/show_addtocart', $code);
    $_showcartbutton = Mage::getStoreConfig('porto_settings/category_grid/show_addtolinks', $code);
    $_imgHtml   = '';
    if ($_imgUrl = $_category->getImageUrl()) {
        $_imgHtml = '<p class="category-image"><img src="'.$_imgUrl.'" alt="'.$this->escapeHtml($_category->getName()).'" title="'.$this->escapeHtml($_category->getName()).'" /></p>';
        $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
    }

?>
   <?php
    $h1_suffix="";
    if($man_value=$_GET['manufacturer']):
        $man_attr = Mage::getModel('catalog/product')->getResource()->getAttribute('manufacturer');
        if ($man_attr->usesSource()) {
            $h1_suffix = " ".$man_attr->getSource()->getOptionText($man_value);
        }
    endif;
   ?>
<?php echo $_imgHtml ?>
<?php
    if(!Mage::getStoreConfig("porto_settings/category/fullwidth_description",$code)){
        if($_description=$_category->getDescription()){
?>
<div class="category-description std">
<?php
            echo $_helper->categoryAttribute($_category, $_description, 'description');
?>
</div>
<?php
        }
    }
?>

<div class="page-title category-title">
    <?php if($this->IsRssCatalogEnable() && $this->IsTopCategory()): ?>
        <a href="<?php echo $this->getRssLink() ?>" class="link-rss"><?php echo $this->__('Subscribe to RSS Feed') ?></a>
    <?php endif; ?>
<?php if($seo_title=$_category->getData('category_seo_name')):?>
<h1><?php print $seo_title;?></h1>
<?php else:?>
<h1><?php echo $_helper->categoryAttribute($_category, $_category->getName(), 'name').$h1_suffix ?></h1>
<?php endif;?>

</div>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<?php if($this->isContentMode()): ?>
    <div class='category-intro'>
        <?php echo $this->getCmsBlockHtml() ?>
    </div>
<?php elseif($this->isMixedMode()): ?>
    <div class='category-intro'>
    <?php echo $this->getCmsBlockHtml() ?>
    </div>
    <?php echo $this->getProductListHtml() ?>

<?php else: ?>
    <?php echo $this->getProductListHtml() ?>
<?php endif; ?>

<?php if ($_description=$_category->getDescription()):?>
    <div class="category-description"><?php echo $_description ?></div>
<?php endif; ?>