<?php foreach ($this->getRegionJson() as $countryCode => $region): ?>
    <script type="text/javascript">countryRegions<?php echo $countryCode; ?> = '<?php echo $region;?>';</script>
<?php endforeach;?>
<!-- адрес есть -->
<ul id="ul-onestepcheckout-address">
<?php if ($this->customerHasAddresses() && !$this->disableAddressBook()): ?>
    <li id="billing-new-address-form-register">
        <label for="billing-address-select" class="onestepcheckout-label-address">
            <?php echo $this->__('Select a billing address from your address book or enter a new address.') ?>
        </label>
        <div class="input-box">
            <?php echo $this->getAddressesHtmlRadio('billing') ?>
        </div>
    </li>
<?php endif; ?>
<!-- -->
    <li id="billing-new-address-form"<?php if ($this->customerHasAddresses()): ?><?php if(!$this->disableAddressBook()):?> style="display:none;"<?php endif; ?><?php endif; ?>>
          <input type="hidden" name="billing[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="billing:address_id" />
          <ul>
              <li>
                  <div class="field">
                      <label for="billing-firstname" class="required"><?php echo $this->__('Firstname') ?><em>*</em></label>
                      <div class="input-box">
                          <input type="text" id="billing-firstname" name="billing[firstname]" data-error="<?php echo $this->__('Please enter the first name.');?>" value="<?php echo $this->htmlEscape($this->getAddress()->getFirstname());?>" title="<?php echo $this->__('Firstname') ?>" class="input-text required-entry" />
                      </div>
                      <?php echo $this->getFieldNote('firstname');?>
                  </div>
              </li>
              <?php if($this->hasField('lastname')):?>
              <li>
                  <div class="field">
                      <label for="billing-lastname" <?php if($this->getRequiredField('lastname')):?>class="required"<?php endif;?>><?php echo $this->__('Lastname') ?><?php if($this->getRequiredField('lastname')):?><em>*</em><?php endif;?></label>
                      <div class="input-box">
                          <input type="text" id="billing-lastname" name="billing[lastname]" data-error="<?php echo $this->__('Please enter the last name.');?>" value="<?php echo $this->htmlEscape($this->getAddress()->getLastname());?>" title="<?php echo $this->__('Lastname') ?>" class="input-text <?php if($this->getRequiredField('lastname')):?>required-entry<?php endif;?>" />
                      </div>
                  </div>
              </li>
              <?php endif;?>
              <?php if($this->hasField('middlename')):?>
               <li>
                  <div class="field">
                      <label for="billing-middlename" <?php if($this->getRequiredField('middlename')):?>class="required"<?php endif;?>><?php echo $this->__('Middlename') ?><?php if($this->getRequiredField('middlename')):?><em>*</em><?php endif;?></label>
                      <div class="input-box">
                          <input type="text" id="billing-middlename" name="billing[middlename]" data-error="<?php echo $this->__('Please enter the middle name.');?>" value="<?php echo $this->htmlEscape($this->getAddress()->getMiddlename());?>" title="<?php echo $this->__('Middlename') ?>" class="input-text <?php if($this->getRequiredField('middlename')):?>required-entry<?php endif;?>" />
                      </div>
                  </div>
              </li>
              <?php endif;?>
              <?php if($this->hasField('company')) :?>
              <li>
                  <div class="field">
                      <label for="billing-company" <?php if($this->getRequiredField('company')):?>class="required"<?php endif;?>><?php echo $this->__('Company') ?><?php if($this->getRequiredField('company')):?><em>*</em><?php endif;?></label>
                      <div class="input-box">
                          <input type="text" id="billing-company" name="billing[company]" data-error="<?php echo $this->__('Please enter the company.');?>" value="<?php echo $this->htmlEscape($this->getAddress()->getCompany());?>" title="<?php echo $this->__('Company') ?>" class="input-text <?php if($this->getRequiredField('company')):?>required-entry<?php endif;?>" />
                      </div>
                  </div>
              </li>
              <?php endif;?>
              <?php if(!$this->isCustomerLoggedIn() && $this->hasField('email')): ?>
              <li>
                  <div class="field">
                      <label for="billing-email" <?php if($this->getRequiredField('email')):?>class="required"<?php endif;?>><?php echo $this->__('Email') ?><?php if($this->getRequiredField('email')):?><em>*</em><?php endif;?></label>
                      <div class="input-box">
                          <input type="text" id="billing-email" name="billing[email]" data-error="<?php echo $this->__('Please enter the email.');?>" value="<?php echo $this->htmlEscape($this->getAddress()->getEmail());?>" title="<?php echo $this->__('Email') ?>" class="input-text validate-email <?php if($this->getRequiredField('email')):?>required-entry<?php endif;?>" />
                      </div>
                  </div>
              </li>
              <?php endif ?>
              <?php if($this->hasField('telephone')) :?>
              <li>
                  <div class="field">
                      <label for="billing-telephone" <?php if($this->getRequiredField('telephone')):?>class="required"<?php endif;?>><?php echo $this->__('Telephone') ?><?php if($this->getRequiredField('telephone')):?><em>*</em><?php endif;?></label>
                      <div class="input-box">
                          <input type="text" id="billing-telephone" name="billing[telephone]" data-error="<?php echo $this->__('Please enter the telephone.');?>" value="<?php echo $this->htmlEscape($this->getAddress()->getTelephone());?>" title="<?php echo $this->__('Telephone') ?>" class="input-text <?php if($this->getRequiredField('telephone')):?>required-entry<?php endif;?>" />
                      </div>
                      <?php echo $this->getFieldNote('telephone');?>
                  </div>
              </li>
              <?php endif;?>
              <!-- address fields -->
              <?php echo $this->getChildHtml();?>

                    <?php if($this->getCreatePassword()):?>
                        <?php if(!$this->isCustomerLoggedIn() && $this->getQuote()->isAllowedGuestCheckout()): ?>
                        <li class="control password-control">
                             <div class="field">
                                 <!-- register -->
                                 <input type="checkbox" <?php if($this->getRegisterGuest()):?>checked="checked"<?php endif;?> class="checkbox" title="<?php echo $this->__('Sign me in this store'); ?>" name="checkout_method" id="checkout_method_in_address" value="register" />
                                 <label for="checkout_method_in_address"><?php echo $this->__('Sign me in this store'); ?></label>
                                <!-- register -->
                            </div>
                        </li>

                        <li class="fields" id="register-customer-password">
                                <div class="field">
                                    <label for="billing:customer_password" class="required"><?php echo $this->__('Password') ?><em>*</em></label>
                                    <div class="input-box">
                                        <input type="password" data-error="<?php echo $this->__('Please enter the password.');?>" name="billing[customer_password]" id="billing:customer_password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password" />
                                    </div>
                                </div>
                                <div class="field">
                                    <label for="billing:confirm_password" class="required"><?php echo $this->__('Confirm Password') ?><em>*</em></label>
                                    <div class="input-box">
                                        <input type="password" data-error="<?php echo $this->__('Please enter the confurm password.');?>" name="billing[confirm_password]" title="<?php echo $this->__('Confirm Password') ?>" id="billing:confirm_password" class="input-text required-entry validate-cpassword" />
                                    </div>
                                </div>
                            </li>

                        <?php else :?>
                         <li class="control">
                            <input type="hidden" name="checkout_method" id="login:register" value="register" checked="checked" />
                         </li>
                        <?php endif;?>
                    <?php endif;?>



            <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
                <?php if(!$this->disableAddressBook()):?>
                    <li class="control">
                          <input type="checkbox" name="billing[save_in_address_book]" value="1" title="<?php echo $this->__('Save in address book') ?>" id="billing:save_in_address_book" class="checkbox" />
                          <label for="billing:save_in_address_book"><?php echo $this->__('Save in address book') ?></label>
                    </li>
                <?php endif;?>
            <?php else:?>
            <li class="no-display">
                <input type="hidden" name="billing[save_in_address_book]" value="1" />
            </li>
            <?php endif; ?>
          </ul>
          <input type="hidden" name="billing[use_for_shipping]" value="1" />
    </li>
</ul>