<?php if ($this->getAgreements()): ?>
<div class="onestepcheckout-agreements-container">
    <ol id="checkout-agreements" class="checkout-agreements">
    <?php foreach ($this->getAgreements() as $_a): ?>
        <li>
            <p class="agree">
                <input type="checkbox" id="agreement-<?php echo $_a->getId()?>" name="agreement[<?php echo $_a->getId()?>]" value="1" class="checkbox" /><label for="agreement-<?php echo $_a->getId()?>"><?php echo $_a->getCheckboxText() ?></label>
            </p>
            <div class="agreement-content agreement-<?php echo $_a->getId()?>">
                <?php if ($_a->getIsHtml()):?>
                    <?php echo $_a->getContent() ?>
                <?php else:?>
                    <?php echo nl2br($this->htmlEscape($_a->getContent())) ?>
                <?php endif; ?>
            </div>
        </li>
    <?php endforeach ?>
    </ol>
</div>
<?php endif;?>